lane :beta do
  
gym(
    project: 'Example.xcodeproj',
    scheme: 'ExampleUITests',
    export_options: {
    method: "enterprise"}  
)

run_tests(
    devices: ["iPhone 6"],
    project: 'Example.xcodeproj',
    scheme: 'ExampleUITests'
)

sonar

snapshot(
    project: 'Example.xcodeproj',
    scheme: 'ExampleUITests',
    devices: ['iPhone 6'],
    output_simulator_logs: true,
    clear_previous_screenshots: true
  )

hockey(
  api_token: "676d0b1a5c4f4d82b069208abfbc84d9",
  ipa: "/Users/devsuri/Desktop/snapshot/Example.ipa",
  notes: "Changelog",
)
end

